---
vagrant:
  required_plugins:
    - vagrant-vbguest
    - vagrant-triggers
vm:
  box: ubuntu/trusty64
  box_url: ubuntu/trusty64
  hostname: 'jujansible'
  memory: '2048'
  cpus: '2'
  chosen_provider: virtualbox
  network:
    private_network: 192.168.56.101
    bridge_network:
      install: 0
      interface_name: ''
    forwarded_port:
      fp1:
        host: '9955'
        guest: '22'
      fp2:
        host: '8080'
        guest: '80'
  post_up_message: ''
  provider:
    virtualbox:
      modifyvm:
        natdnshostresolver1: on
  synced_folder:
    vagrant:
      owner: www-data
      group: www-data
      source: ./
      target: /vagrant
      sync_type: default
      rsync:
        args:
          - '--verbose'
          - '--archive'
          - '-z'
        exclude:
          - .vagrant/
        auto: 'false'
    www:
      owner: www-data
      group: www-data
      source: ./www
      target: /var/www
      sync_type: default
      rsync:
        args:
          - '--verbose'
          - '--archive'
          - '-z'
        exclude:
          - .vagrant/
        auto: 'false'
  usable_port_range:
    start: 10200
    stop: 10500
ssh:
  username: vagrant
  password: vagrant
  host: null
  port: null
  guest_port: null
  # private_key_path: "~/.ssh/id_rsa"
  keep_alive: true
  forward_agent: true
  forward_x11: false
  shell: 'bash -l'

provision:
  ansible:
    playbook: ansible/playbook.yml
    inventory_path: ''
    limit: 'all'

    settings:
      timezone: "America/Bogota"
      php:
        ini:
          memory_limit: "512M"
          max_execution_time: "120"
          realpath_cache_size: "32K"
          upload_max_filesize: "64M"
          error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
          display_errors: "On"
          html_errors: "On"
          timezone: "America/Bogota"
        packages:
          - php5-cli
          - php5-fpm
          - php5-mysql
          - php5-xdebug
          - php5-curl
          - php5-memcached
          - php5-gd
      nginx:
        conf:
          client_max_body_size: "8M"
        vhosts:
          - server_name: vagrant.dev
            server_aliases:
              - www.vagrant.dev
            www_root: /var/www
            listen_port: '80'
            index_files:
              - phpinfo.php
              - index.html
              - index.htm
              - index.php
            envvars:
              - 'APP_ENV dev'
          - server_name: shock.dev
            server_aliases:
              - www.shock.dev
            www_root: /var/www/shock-com-co
            listen_port: '80'
            index_files:
              - index.html
              - index.htm
              - index.php
            envvars:
              - 'APP_ENV dev'
      mysql:
        root_password: 123
        dbs:
          - database: shock
            user: shock
            password: shock
          - database: cromos
            user: cromos
            password: cromos

