---
  - name: Update apt
    sudo: yes
    apt: update_cache=yes

  - name: Install System Packages
    sudo: yes
    apt: pkg={{ item }} state=latest
    with_items:
      - curl
      - wget
      - python-software-properties
      - unzip
      - htop

  - name: Configure the timezone
    sudo: yes
    template: src=timezone.tpl dest=/etc/timezone

  - name: More Configure the timezone
    sudo: yes
    file: src=/usr/share/zoneinfo/{{ settings.timezone }} dest=/etc/localtime state=link force=yes backup=yes

  - name: Set the hostname
    hostname: name={{ hostname }}

  - name: Update /etc/hosts
    lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ hostname }}' owner=root group=root mode=0644

