---
# nginx variables

nginx_default_conf_path: /etc/nginx/conf.d/default.conf
nginx_available_vhost_path: /etc/nginx/sites-available
nginx_enabled_vhost_path: /etc/nginx/sites-enabled
nginx_template: default.tpl
