---
- name: Install Nginx
  sudo: yes
  apt: pkg=nginx state=latest force=yes

- name: Setting custom nginx.conf variables
  lineinfile: dest={{ nginx_default_conf_path }}
              create=yes
              state=present
              regexp='{{ item.key }} '
              line='{{ item.key }} {{ item.value }};'
  with_dict: settings.nginx.conf
  notify: Restart nginx

- name: Change default nginx site
  sudo: yes
  template: src={{ nginx_template }} dest={{ nginx_available_vhost_path }}/{{ item.server_name }}.conf
  with_items: settings.nginx.vhosts
  notify: Restart nginx

- name: Enabling nginx sites.
  file: >
    src={{ nginx_available_vhost_path }}/{{ item.server_name }}.conf
    dest={{ nginx_enabled_vhost_path }}/{{ item.server_name }}.conf
    state=link
  with_items: settings.nginx.vhosts
  notify: Restart nginx
